# Linear and quadratic programming with `cvxpy`

In this notebook, we will use the `cvxpy` Python library to find the solution for a linear program. Since linear programs are always convex optimization problems, we can use `cvxpy` for this purpose.

In [1]:
!pip install cvxpy

  Using cached cvxpy-1.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)
  Using cached ecos-2.0.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (220 kB)
  Using cached setuptools-67.6.1-py3-none-any.whl (1.1 MB)
  Using cached osqp-0.6.2.post8-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (298 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 37.7 MB/s eta 0:00:0000:010:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 23.8 MB/s eta 0:00:00:00:01
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.5.1
    Uninstalling setuptools-65.5.1:
      Successfully uninstalled setuptools-65.5.1


In [2]:
import cvxpy as cp
import numpy as np

## Example 

Let's consider the linear program 

$$ \min x_1 + x_2 $$

subject to

$$
x_1 \geq 1,\ x_1 + 2x_2 \geq 2
$$

Let's rewrite this using matrices and vectors as

$$ \min \mathbf{c}^\mathsf{T} \mathbf{x} $$

subject to

$$
A \mathbf{x} \leq \mathbf{b}
$$

where 

$$
\mathbf{c} = \begin{bmatrix} 1 \\ 1 \end{bmatrix},\ A = \begin{bmatrix} -1 & 0 \\ -1 & -2 \end{bmatrix},\ \mathbf{b} = \begin{bmatrix} -1 \\ -2 \end{bmatrix}
$$

We first create our matrices and vectors using `numpy`.

In [3]:
A = np.array([
    [-1,0], [-1,-2]
])
b = np.array([-1,-2])
c = np.array([1,1])

Now we create our variable just as in the previous notebook.

In [4]:
x = cp.Variable(2)

We define our constraints using matrix-vector operations with the symbol `@`. We only have one constraint since we bundled it all together using vectors.

In [5]:
constraints = [A @ x <= b]

We are ready to define our problem and solve it.

In [6]:
prob = cp.Problem(cp.Minimize(c.T @ x), constraints)

In [7]:
prob.solve()

1.500000000001771

The value printed out is the primal optimal value. We can also ask for the optimal solution (i.e. the value of $\mathbf{x}$ that realizes this optimal value).

In [8]:
x.value

array([1. , 0.5])

We have two constraints, so therefore we have two dual variables, and we can ask for the optimal solution to the dual problem as well.

In [9]:
prob.constraints[0].dual_value

array([0.5, 0.5])

Quadratic programs can be coded up similarly using matrices and vectors.

## Exercise 1

Use `cvxpy` to solve Question 7.6 in Diesenroth. Show the optimal value and the optimal solution for $\mathbf{x}$. 

In [13]:
A2 = np.array([
    [2,2], [2,-4], [-2, 1], [0,-1], [0, 1]
])
b2 = np.array([33, 8, 5, -1, 8])
c2 = np.array([5,3])

In [12]:
x2 = cp.Variable(2)

In [15]:
constraints2 = [A2 @ x2 <= b2]

In [21]:
prob2 = cp.Problem(cp.Minimize(c2.T @ x2), constraints2)
prob2.solve()

-6.999999989642528

In [22]:
x2.value

array([-2.,  1.])

In [23]:
prob2.constraints[0].dual_value

array([3.67587829e-10, 4.22425579e-10, 2.50000000e+00, 5.50000000e+00,
       1.40506072e-10])

## Exercise 2

Use `cvxpy` to solve Question 7.7 in Diesenroth. Show the optimal value and the optimal solution for $\mathbf{x}$. 

In [24]:
A3 = np.array([
    [1,0], [-1,0], [0, 1], [0,-1]
])
b3 = np.array([1, 1, 1, 1])
c3 = np.array([5,3])
Q = np.array([[2,1], [1,4]])

In [25]:
x3 = cp.Variable(2)

In [26]:
constraints3 = [A3 @ x3 <= b3]

In [27]:
prob3 = cp.Problem(cp.Minimize(c3.T @ x3), constraints3)
prob3.solve()

-7.999999986442335

In [28]:
x3.value

array([-1., -1.])

In [29]:
prob3.constraints[0].dual_value

array([6.79743949e-09, 5.00000001e+00, 2.48278298e-09, 3.00000000e+00])